default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: username
  password: password
  host: localhost

development:
  <<: *default
  database: simplblog_development

staging:
  <<: *default
  database: simplblog_staging

production:
  <<: *default
  database: simplblog_production
  username: ArbabHR
  password: <%= ENV['ARBABHR_DATABASE_PASSWORD'] %>
